wotoog_note:
    resource: "@WotoogNoteBundle/Resources/config/routing.yml"
    prefix:   /notes

wotoog_blog_posts:
    resource: "@WotoogBlogBundle/Resources/config/routing/post.yml"
    prefix:   /blogs/{blog_id}/posts
    requirements: {blog_id: \d+}

wotoog_blog:
    resource: "@WotoogBlogBundle/Resources/config/routing/blog.yml"
    prefix:   /blogs

wotoog_club:
    resource: "@WotoogClubBundle/Resources/config/routing.yml"
    prefix:   /clubs

wotoog_user:
    resource: "@WotoogUserBundle/Resources/config/routing.yml"
    prefix:   /users

wotoog_counter:
    resource: "@WotoogCounterBundle/Resources/config/routing.yml"
    prefix:   /

wotoog_home:
    resource: "@WotoogHomeBundle/Resources/config/routing.yml"
    prefix:   /home

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_imagine:
    resource: .
    type:     imagine